config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "surveys#index"

  
  resources :users
  resources :answers
  resources :surveys do
    resources :questions
    get :report
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :question_id, presence: true
  validate :pick_an_answer
  validate :pick_more_answers
  

  def pick_an_answer
    if question.question_type == "multiple_choice"
      if option.blank?
        errors.add(:multiple_choice, 'select one answer')
      end 
    end 
  end 
 
  def pick_more_answers
    if question.question_type == "multi_part"
      if option1 == "0"  && option2 == "0" && option3 == "0" && option4 == "0"
        errors.add(:multi_part, 'select an answer') 
      end 
    end 
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers, dependent: :destroy

  validates :title, presence: true
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  belongs_to :user

  before_create :titilize_title

  validates :title, presence: true 

  def titilize_title
    self.title = self.title.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :surveys, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :authenticate_user!, only: :create
  
  def new
    @answer = Answer.new
  end

  def create
    question = Question.find(params[:answer][:question_id])
    survey = Survey.find(params[:answer][:survey_id])
    @answer = Answer.new(answer_params)
  
    if @answer.save 
      if question != question.survey.questions.last
        questions = question.survey.questions
        next_question = survey.questions.where('id > ?', question.id).order(:id).first

        redirect_to survey_path(question.survey, question_id: next_question.id)
      else 
        redirect_to root_path
      end
    else
      redirect_to survey_path(question.survey, question_id: params[:answer][:question_id]), alert: @answer.errors.full_messages[0]
    end
  end

private
  def answer_params 
    params.require(:answer).permit(:option, :option1, :option2, :option3, :option4, :question_id, :question_type, :open_ended, :multi_part, :multiple_choice) 
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def new 
    @question = Question.new
  end

  def create
    if params[:type].blank?
      @question = Question.new(question_params)
     
    if params[:title].blank?
      flash[:notice] = "Please provide a question"
      redirect_to :back
    elsif
       @question.save
      flash[:notice] = "Question successfully created"
      redirect_to survey_path(@question.survey, question_id: @question.id)
    else 
      render :new
    end 
  else
    redirect_to new_survey_question_path(params[:survey_id], question_type: params[:type])
  end
end

  def edit
    @question = Question.find(params[:id])
  end 

  def update
    @question = Question.find(params[:id])

    if @question.update(update_question_params)
      flash[:notice] = "Question successfully updated"
      redirect_to survey_path(@question.survey, question_id: @question.id)
    else 
      redirect_to edit_survey_question_path(params[:survey_id], question_type: params[:question_type])
    end 
  end 

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Question removed"
    redirect_to survey_path(@question.survey, question_id: @question.survey.questions.first)
  end

private 
  def question_params
    params.permit(:title, :option1, :option2, :option3, :option4, :survey_id, :question_id, :question_type)
  end 

  def update_question_params
    params.require(:question).permit(:title, :option1, :option2, :option3, :option4, :survey_id, :question_id, :question_type)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  #include SurveyReportsGenerator
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show
 
  def index
    @surveys = Survey.all
  end

  def show 
    
    @survey = Survey.find(params[:id])
    begin
      @question = @survey.questions.find(params[:question_id])
    rescue ActiveRecord::RecordNotFound
      @question = nil
    end
  end

  def report
    @survey = Survey.find(params[:survey_id]) 
  end

  def new 
    @survey = current_user.surveys.build
  end 

  def create
    @survey = current_user.surveys.build(survey_params)

    if @survey.save
      flash[:notice] = "Survey successfully created"
      redirect_to surveys_path
    else
      render :new
    end 
  end 

  def edit
    @survey = Survey.find(params[:id])
  end 

  def update 
    @survey = Survey.find(params[:id])

    if @survey.update(survey_params)
      flash[:notice] = "Survey successfully updated"
      redirect_to survey_path(@survey, question_id: @survey.questions.first.id)
    else 
      render :edit
    end 
  end 

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    flash[:notice] = "Survey deleted"
    redirect_to surveys_path
  end 

  
private
  def survey_params
    params.require(:survey).permit(:title, :survey_id, :question_id, :question_type)
  end 
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.slim
-if answer.question.question_type == 'multiple_choice'
  = form_with model: answer, html:{multipart: false} do |form|
    div 
      = form.hidden_field :question_id, value: answer.question_id 
    div 
      = form.hidden_field :survey_id, value: survey.id 
    div 
      = form.hidden_field :question_type, value: 'multiple_choice'
    div 
      = form.label "#{answer.question.option1}"
    div 
      = form.radio_button :option, answer.question.option1
    br
    div 
      = form.label "#{answer.question.option2}"
    div 
      = form.radio_button :option, answer.question.option2 
    br 
    div 
      = form.label "#{answer.question.option3}"
    div 
      = form.radio_button :option , answer.question.option3
    br
    div 
      = form.label "#{answer.question.option4}"
    div 
      = form.radio_button :option , answer.question.option4
    div 
      - if answer.question != survey.questions.last
        = form.submit 'Next'
      - else 
        = form.submit 

-elsif answer.question.question_type == 'open_ended'
  = form_with model: answer do |form|
    div 
      = form.hidden_field :question_id, value: answer.question_id 
    div 
      = form.hidden_field :survey_id, value: survey.id 
    div 
      = form.hidden_field :question_type, value: 'open_ended'
    div 
      = form.label :answer
    div 
      = form.text_field :open_ended, required: true
    div 
      - if answer.question != survey.questions.last
        = form.submit 'Next'
      - else 
        = form.submit 

-else answer.question.question_type == 'multi_part'
  = form_with model: answer, html:{multipart: true} do |form|
    div 
      = form.hidden_field :question_id, value: answer.question_id 
    div 
      = form.hidden_field :survey_id, value: survey.id 
    div 
      = form.hidden_field :question_type, value: 'multi_part'
    div 
      = form.label "#{answer.question.option1}"
    div 
      = form.check_box(:option1, {}, "#{answer.question.option1}")
    br
    div 
      = form.label "#{answer.question.option2}"
    div 
      = form.check_box(:option2, {}, "#{answer.question.option2}")
    br 
    div 
      = form.label "#{answer.question.option3}"
    div 
      = form.check_box(:option3, {}, "#{answer.question.option3}")
    br 
    div 
      = form.label "#{answer.question.option4}"
    div 
      = form.check_box(:option4, {}, "#{answer.question.option4}")
    div 
      - if answer.question != survey.questions.last
        = form.submit 'Next'
      - else 
        = form.submit 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveysApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
        <% if user_signed_in? %>
          <%= current_user.email %><br>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.slim
-if params[:question_type].blank?
  =form_with url: survey_questions_path  do |form|
    div 
      = form.label :type
    div 
      = form.select :type, [["multiple_choice", "multiple_choice"], ["open ended", "open_ended"], ["multi part", "multi_part"]]
    div 
      =form.submit "Next"
      
-elsif params[:question_type] == "multiple_choice"
  = form_with url: survey_questions_path do |form|
    div 
      = form.hidden_field :question_type, value: 'multiple_choice'
    div 
      = form.label :title
    div 
      = form.text_area :title, required: true
    div 
      = form.label :option1
    div 
      = form.text_field :option1, required: true
    br 
    div 
      = form.label :option2
    div 
      = form.text_field :option2, required: true
    br 
    div 
      = form.label :option3
    div 
      = form.text_field :option3, required: true
    br 
    div 
      = form.label :option4
    div 
      = form.text_field :option4, required: true
    
    div 
      = form.submit

-elsif params[:question_type]  ==  "open_ended"
  =form_with url: survey_questions_path  do |form|
    div 
      = form.hidden_field :question_type, value: 'open_ended'
    div 
      = form.label :title
    div 
      = form.text_area :title, required: true
    div 
      = form.submit

-else params[:question_type] == "multi_part"
  = form_with url: survey_questions_path do |form|
    div 
      = form.hidden_field :question_type, value: 'multi_part'
    div 
      = form.label :title
    div 
      = form.text_area :title, required: true
    br 
    div 
      = form.label :option1
    div 
      = form.text_field :option1, required: true
    br 
    div 
      = form.label :option2
    div 
      = form.text_field :option2, required: true
    br 
    div 
      = form.label :option3
    div 
      = form.text_field :option3, required: true
    br 
    div 
      = form.label :option4
    div 
      = form.text_field :option4, required: true
    
    div 
      = form.submit

  

app/views/questions/edit.html.slim
h3 
  = link_to "Home", root_path
h1 Edit Question 

-if @question.question_type == 'multiple_choice'
  =form_with model: [@question.survey, @question] do |form|
    div 
      = form.label :title
    div 
      = form.text_area :title
    br 
    div 
      = form.label :option1
    div 
      = form.text_field :option1
    br 
    div 
      = form.label :option2
    div 
      = form.text_field :option2
    br 
    div 
      = form.label :option3
    div 
      = form.text_field :option3
    br 
    div 
      = form.label :option4
    div 
      = form.text_field :option4 

    div 
      = form.submit

-elsif @question.question_type == 'open_ended'
  =form_with model: [@question.survey, @question] do |form|
    div 
      = form.label :title
    div 
      = form.text_area :title
    div 
      = form.submit

-else @question.question_type == 'multi_part'
  =form_with model: [@question.survey, @question] do |form|
    div 
      = form.label :title
    div 
      = form.text_area :title
    br 
    div 
      = form.label :option1
    div 
      = form.text_field :option1
    br 
    div 
      = form.label :option2
    div 
      = form.text_field :option2
    br 
    div 
      = form.label :option3
    div 
      = form.text_field :option3
    br 
    div 
      = form.label :option4
    div 
      = form.text_field :option4 

    div 
      = form.submit

app/views/questions/new.html.slim
h3 
  = link_to "Home", root_path
h1 Question 
h3 
  div 
    = render "form", question: @question, survey: @survey

app/views/surveys/_form.html.slim
= form_with model: survey do |form|
  div 
    = form.label :title
  div 
    = form.text_field :title
  div  
    = form.submit

app/views/surveys/edit.html.slim
h3 
  = link_to "Home", root_path 

h1 Edit Survey 

h3 
  div 
     = render "form", survey: @survey

app/views/surveys/index.html.slim
-if user_signed_in? 
  div 
    = link_to 'sign out', destroy_user_session_path, data: {method: :delete}

  h1 Surveys
  ul
    -@surveys.each do |survey|
       - if survey.user == current_user
        li 
          = link_to survey.title, survey_path(survey, question_id: survey.questions.first)
       
        div 
          = link_to "Survey Report", survey_path(survey) + '/report'
       
  div 
    = link_to "Create Survey", new_survey_path
  
-else
  = link_to "login", new_user_session_path 
  div 
  = link_to "sign up", new_user_registration_path
  h1 Surveys
  ul
    -@surveys.each do |survey|
      li 
        = link_to survey.title, survey_path(survey, question_id: survey.questions.first)
      p 
        | created by: 
        = survey.user.email
      br 

app/views/surveys/new.html.slim
h3 
  = link_to "Home", root_path 

h1 Create Survey 

h3 
  div 
    = render "form", survey: @survey

app/views/surveys/report.html.slim
h3
  = link_to "Home", root_path

h1
  = @survey.title

-@survey.questions.each do |question|
  - question_service = SurveyReportsGenerator.new(question: question)
  = question.question_type
  div 
    = question.title 
  -if question.question_type == "multiple_choice"
    br
      | number of people that answered this question ; 

      = question_service.count_answers
      - averages = question_service.average_answer
      ul
        -averages.each do |option, average|
          li 
            = "#{option} average: #{average}"

          
  -elsif question.question_type == "multi_part"
    br
    | number of people that answered this question ; 

    = question_service.count_answers
    - averages = question_service.average_answer
    ul
      -averages.each do |option, average|
        li 
          = "#{option} average: #{average}"    
  -else
    ul 
      -question.answers.each do |answer|
        = answer.open_ended
      
  

app/views/surveys/show.html.slim
-if user_signed_in? && @survey.user == current_user
  h3 
    = link_to "Home", root_path
  -if @question.present?
    h1 = @survey.title.titleize
    br 
    - @survey.questions.each do |question|
      div 
        =  link_to "edit '#{question.title}'", edit_survey_question_path(question.survey, question)
        br
        = link_to "Delete Question", survey_question_path(@survey, @question), method: :delete, data: {confirm: "Are you sure you want to delete these questions?"}
        hr 
    br
  div 
    = link_to "Add Question", new_survey_question_path(@survey)
  div 
    = link_to "Edit survey", edit_survey_path(@survey)
  div  
      = link_to "Delete Survey", survey_path, method: :delete, data: {confirm: "Are you sure you want to delete this survey?"}
    
- else 
  -if @question.present? 
    h3 
      = link_to "Home", root_path
    - if @question.present?
      h1 = @survey.title
      br 
      div 
        = @question.title 
      br
        br
      = render 'answers/form', { answer: @question.answers.new(), survey: @survey}

    - else 
      h1 
        = @survey.title
      p This survey has no questions
  - else 
    h1  #{@survey.title}   
    p This survey has no questions

app/views/users/index.html.slim
h1 Surveys

ul 
  li 
    = link_to "Create Surveys", new_survey_path